[server]
certificate = "keys/cert.pem"
server_addr = "127.0.0.1"
tls_hostname = "shroom.server"

[proxy]
proxy_id = 1
timeout = "30s"
blacklist_file = "blacklist/ipsum.txt"

[[mappings]]
from_port = 9484
to = "wss://127.0.0.1:8484/shroom"

[[mappings]]
from_port = 9485
to = "wss://127.0.0.1:8485/shroom"